<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Dameview.Core/Dameview.Core.csproj" />
    <ProjectReference Include="../../src/Dameview.Win32/Dameview.Win32.csproj" />
    <ProjectReference Include="../../src/Dameview/Dameview.csproj" />
  </ItemGroup>

</Project>
