<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <RootNamespace>Dameview.UI</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Dameview.Win32/Dameview.Win32.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Dameview" />
    <InternalsVisibleTo Include="Dameview.Tests" />
  </ItemGroup>

</Project>
